spring:
  application:
    name: monitoring-demo

  security:
    user:
      name: user
      password: password
      roles: admin

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health","prometheus", "metrics", "customEndpoint" ]
  endpoint:
    health:
      show-details: when_authorized
    metrics:
      enabled: true
    prometheus:
      enabled: true
server:
  port: 8080

